### ISSUE TITLE
Playbook Tasks Should Be Idempotent

### ISSUE THREAD

**Issue by paulcalabro** [wazuh/wazuh-ansible#100]
By this I mean, if you run a playbook twice the first playbook run should bring about the desired state while the second playbook run reports zero changes.  This allows for better reporting of things that are actually changing in your environment. Otherwise, it looks like your environment is constantly being updated in reporting consoles. I did a quick scan of the code. I think a few things that would need to be updated are any state checks using execs (you can add params to them so they report correctly based on some test) as well repos (if you pin versions, there's no harm having the repos enabled and not constantly disabled and re-enabled). It's also usually cheaper when tasks are not unnecessarily run every time.

**Comment by paulcalabro** [comment]
Example of tasks being reportedly marked as "changed":

https://www.dropbox.com/s/s8wzehge78wwty5/Screenshot%202018-12-11%2015.37.50.png?dl=0

**Comment by SitoRBJ** [comment]
Hello @paulcalabro,

You are right, right now there are tasks that report changes having released a playbook twice in a row.

We will review the use of execs to check the states using parameters as your advice and we will try to add conditions to certain tasks so that they are not executed when it is not necessary. We will start work as soon as possible.

Thank you very much for your collaboration, please feel free to comment any doubt, improvement or inconvenience that you see appropriate. Contributions like yours from the community are enormously valuable. Thank you again. 

Kind regards,

Alfonso Ruiz-Bravo

**Comment by paulcalabro** [comment]
Happy to help! If I have some time this week or next, I'll try to make a PR to help make things idempotent.

**Comment by SitoRBJ** [comment]
Hello @paulcalabro,

Any contribution is welcome. 

Thank you very much for your interest and for your help. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by rshad** [comment]
Hi @paulcalabro ,

In the PR https://github.com/wazuh/wazuh-ansible/pull/206. we applied the corresponding changes to make sure that all tasks in each role are idempotence.

Kind regards,

Rshad
