### ISSUE TITLE
 wazuh-certs-tool.sh v4.8 is not available to download #890 

### ISSUE THREAD

**Issue by SirStephanikus** [wazuh/wazuh-ansible#1173]
`fatal: [test-instance -> localhost]: FAILED! => {"changed": false, "dest": "/../playbooks/indexer/certificates/wazuh-certs-tool.sh", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://packages.wazuh.com/4.8/wazuh-certs-tool.sh"}`

The problem is inside the file **roles/wazuh/vars/repo.yml**
`certs_gen_tool_version: 4.8  # Url of certificates generator tool certs_gen_tool_url: "https://packages.wazuh.com/{{ certs_gen_tool_version }}/wazuh-certs-tool.sh"`

4.8 is not available yet but it is hardcoded inside the vars file. I had to fix it by switching it to 4.7

IMHO, it should be updated and also a hint at the top of the documentation.

**Comment by rauldpm** [comment]
Hello @SirStephanikus

I have not been able to reproduce your problem, both the 4.7.2 branch and the v4.7.x tags have version 4.7 in the file you specify.

As you indicate, version `4.8` of Wazuh has not yet been published since it is in the development phase, please make sure that the cloned branch is correct and that you are not on the `4.8.0` branch

Is it possible that you used the `master` branch for the deployment instead of using the latest `v4.7.1` production tag? The `master` branch corresponds to the development version `4.9.0` and contains a reference to version `4.8`. I have already communicated this to the responsible team so that they can fix it, but please make sure to use the latest production version, which is currently `v4.7.1`, for that, after cloning the repository, you can change the row using the following command:

> git checkout v4.7.1

**Comment by SirStephanikus** [comment]
> Hello @SirStephanikus
> 
> I have not been able to reproduce your problem, both the `4.7.2` branch and the `v4.7.x` tags have version `4.7` in the file you specify.
> 
> As you indicate, version `4.8` of Wazuh has not yet been published since it is in the development phase, please make sure that the cloned branch is correct and that you are not on the `4.8.0` branch
> 
> Is it possible that you used the `master` branch for the deployment instead of using the latest `v4.7.1` production tag? The `master` branch corresponds to the development version `4.9.0` and contains a reference to version `4.8`. I have already communicated this to the responsible team so that they can fix it, but please make sure to use the latest production version, which is currently `v4.7.1`, for that, after cloning the repository, you can change the branch using the following command:
> 
> > git checkout v4.7.1
> 
> I opened the following issue to fix it: #1187

Hello Raul

Thanks for your detailed reply. 

YES, you are right. I just took the git clone link from the repos landing page.
It doesn't matter who is to blame, you taught me to look closer to the tags and not to the "latest".

Thanks a lot.
