### ISSUE TITLE
ANSIBLE single-node RHEL System, broken Indexer variable

### ISSUE THREAD

**Issue by SirStephanikus** [wazuh/wazuh-ansible#1174]
```
TASK [../roles/wazuh/wazuh-indexer : Install Wazuh indexer] **********************************************************************************************************************************
fatal: [rocky-8-testme]: FAILED! => {"changed": false, "failures": ["No package wazuh-indexer-4.9.0 available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

And the corresponding part in Ansible (RedHat):

`  - name: Install Wazuh indexer
    package:
      name: wazuh-indexer-{{ indexer_version }}
      state: present
    register: install
    tags: install
`

The problem is:

There is no package with the name "wazuh-indexer-4.9.0"!

```
dnf search wazuh

wazuh-indexer.x86_64 : Wazuh indexer is a search and analytics engine for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
```

```
dnf info wazuh-indexer

Letzte Prüfung auf abgelaufene Metadaten: vor 0:08:00 am Di 26 Dez 2023 16:13:02 CET.
Verfügbare Pakete
Name         : wazuh-indexer
Version      : 4.7.1
Release      : 1
Architecture : x86_64
Size         : 673 M
Quelle       : wazuh-indexer-4.7.1-1.src.rpm
Repository   : wazuh_repo
Summary      : Wazuh indexer is a search and analytics engine for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
URL          : https://www.wazuh.com/
Lizenz       : GPL
Description  : Wazuh indexer is a near real-time full-text search and analytics engine that gathers security-related data into one platform. This Wazuh central component indexes and stores alerts generated by the Wazuh server. Wazuh indexer can be configured as a single-node or multi-node cluster, providing scalability and high availability. Documentation can
             : be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
```

DNF only knows wazuh-indexer and not a combination with a version number ... and the package provided hat the version 4.7.1

Have you guys even tested the Playbook ???

**Comment by davidcr01** [comment]
Hello. The issue you are involved in is related to our branches and releases system. In this part of the [README.md](https://github.com/wazuh/wazuh-ansible/blob/master/README.md#branches) we specify that the `master` branch contains the latest code. It exists because it is needed to work in the new versions of Wazuh.

Currently, the `master` branch is the numbered branch `4.9.0`. Our latest tag is `v4.7.1`, you can check it here. https://github.com/wazuh/wazuh-ansible/releases/tag/v4.7.1. The `latest` tag in the release title indicates it. This is the most recent and stable version of Wazuh. The rest of the versions higher than it is being developed.

So then, I think you tried to deploy Wazuh using Ansible in a development branch where the packages are not published yet as this version is currently being developed. I suggest you move to the correct tag before deploying Wazuh
