### ISSUE TITLE
Download certificates generation tool error when using Ansible play book and V 4.9

### ISSUE THREAD

**Issue by mrjson79** [wazuh/wazuh-ansible#1199]
Hi
I receive the following when doing deploy with Ansible for a Wazuh cluster.
![image](https://github.com/wazuh/wazuh-ansible/assets/88654489/2dd6ad96-e3e2-46c6-a9d6-2cd8ec3eb291)

However changing to v 4.7.2 doesn't throw that error.

Regards,
/Anders.

**Comment by mrjson79** [comment]
this was solved by actually cloning the correct version of the repo.

**Comment by PUDPUD** [comment]
I have the same issue
TASK [../roles/wazuh/wazuh-indexer : Local action | Download certificates generation tool] **********************************************************************************************************************
fatal: [UBT-WZH-PRD-001 -> localhost]: FAILED! => {"changed": false, "dest": "/home/casper/downloads/Ansible/playbooks/indexer/certificates/wazuh-certs-tool.sh", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://packages.wazuh.com/4.9/wazuh-certs-tool.sh"}

**Comment by davidcr01** [comment]
Hello. The issue you are involved in is related to our branches and releases system. In this part of the [README.md](https://github.com/wazuh/wazuh-ansible/blob/master/README.md#branches) we specify that the `master` branch contains the latest code. It exists because it is needed to work in the new versions of Wazuh.

Currently, the `master` branch is the numbered branch `4.9.0`. Our latest tag is `v4.7.2`, you can check it here. https://github.com/wazuh/wazuh-ansible/releases/tag/v4.7.2. The `latest` tag in the release title indicates it. This is the most recent and stable version of Wazuh. The rest of the versions higher than it is being developed.

So then, I think you tried to deploy Wazuh using Ansible in a development branch where the packages are not published yet as this version is currently being developed. I suggest you move to the correct tag before deploying Wazuh.
