### ISSUE TITLE
Repository 5.x does not have release file 

### ISSUE THREAD

**Issue by opentokix** [wazuh/wazuh-ansible#1278]
Trying to run the latest playbook on Ubuntu 22.04 and I get this error. 

TASK [../roles/wazuh/ansible-wazuh-agent : Debian/Ubuntu | Add Wazuh repositories] ************************************************************************************************
fatal: [hostname.domain.tld]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://packages.wazuh.com/5.x/apt stable Release' does not have a Release file."}

**Comment by rauldpm** [comment]
Hello @opentokix 

This error is expected since `5.x` corresponds to version `5.0.0` of Wazuh, which has not been published yet (we just published `v4.7.4`), this occurs because you are deploying with the `master` branch, which corresponds to said version in development (`5.0.0`)

You can check the Wazuh version that corresponds to the branch/tag you are using in the following file, where {branch_tag} is the branch or tag selected 

- https://github.com/wazuh/wazuh-ansible/blob/{branch_tag}/VERSION

Some examples:

- https://github.com/wazuh/wazuh-ansible/blob/master/VERSION
- https://github.com/wazuh/wazuh-ansible/blob/4.8.0/VERSION
- https://github.com/wazuh/wazuh-ansible/blob/v4.7.4/VERSION



If you want to perform a deployment, I recommend that you change the reference of the GitHub repository to the `v4.7.4` tag using the following command

- git pull
- git checkout v4.7.4

Also, I think you should follow the deployment guide where all the steps are detailed.

- https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/index.html

**Comment by opentokix** [comment]
I did follow the steps on that documentation site.

**Comment by rauldpm** [comment]
If you have followed the steps then you should not have gotten that error, make sure that you have executed the command correctly and that you have followed all the documentation since the branch change is done here

https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html#playbooks-and-roles

> cd /etc/ansible/roles/
> sudo git clone --branch v4.7.4 https://github.com/wazuh/wazuh-ansible.git
> ls

The `v4.7.4` tag points to `4.x` and not `5.x`, indicating that the branch switch has not been made, so you are using the `master` branch

https://github.com/wazuh/wazuh-ansible/blob/7c8ee86eed51099d3ea8937dca830e7b8f7e3a3a/roles/wazuh/check-packages/scripts/check_packages.sh#L12

**Comment by rauldpm** [comment]
Closed due to inactivity
