### ISSUE TITLE
Agent install fails on 18.04 with Default-Start contains no runlevels

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-ansible#170]
I received the following when installing via Ansible on Ubuntu 18.04.

TASK [ansible-wazuh-agent : Linux | Ensure Wazuh Agent service is started and enabled] *******************************************************************************************************
task path: /<parent directory of wazuh-ansible>/wazuh-ansible/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml:168
fatal: [192.168.x.x]: FAILED! => {"changed": false, "msg": "Unable to enable service wazuh-agent: Synchronizing state of wazuh-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable wazuh-agent\ninsserv: warning: script 'K01wazuh-agent' missing LSB tags and overrides\ninsserv: script wazuh-agent is not an executable regular file, skipped!\nupdate-rc.d: error: wazuh-agent Default-Start contains no runlevels, aborting.\n"}

**Comment by jm404** [comment]
Hello @alphaDev23!

Thank you for reporting this! I would like to know more about which environment are you running (Ansible version, Wazuh version...) in order to replicate the problem.

I'm looking forward to your response.

Regards!

**Comment by manuasir** [comment]
Hello @alphaDev23 ,

Did you get anything on this issue? I just wanted to follow up on this.

Regards

**Comment by rshad** [comment]
Hi @alphaDev23 ,

Please check the changes in this [PR#206]https://github.com/wazuh/wazuh-ansible/pull/206.

We fixed many errors, and the one you reported is included. Wazuh's deployment with Ansible was verified to be successfully made in different distribution and Ubuntu 18.* is one of those.

We're closing this issue due to the inactivity from your side.

Please if you still face this issue do not hesitate to contact us again.

Kind regards,

Rshad,
