### ISSUE TITLE
Failed Install: No package matching 'wazuh-agent' is available

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-ansible#217]
I removed the previous wazuh key.  Why is the playbook referring to the same key, not updating the key, and failing?  Please advise.  These ansible install issues are becoming very frustrating and it doesn't appear that the wazuh-agent playbook accounts from even the most basic use cases such as the agent previously being installed, previous pgp keys, etc./

fatal: [192.168.x.x]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.x.x closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1565562510.11-14630914280787/AnsiballZ_apt_repository.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1565562510.11-14630914280787/AnsiballZ_apt_repository.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1565562510.11-14630914280787/AnsiballZ_apt_repository.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_apt_repository_payload_HIlhWB/__main__.py\", line 554, in <module>\r\n  File \"/tmp/ansible_apt_repository_payload_HIlhWB/__main__.py\", line 546, in main\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 559, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: W:GPG error: https://packages.wazuh.com/3.x/apt stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 96B3EE5F29111145, E:The repository 'https://packages.wazuh.com/3.x/apt stable InRelease' is not signed.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by jm404** [comment]
Hi @alphadev23,

I'm sorry to hear you are having trouble with the installation process. Let's troubleshoot this!

I rechecked the Installation of GPG keys which worked fine, also working on our tests. I also verified the links that are up and working.

I see you are using a custom script (`AnsiballZ_apt_repository.py`), so I guess you are using our playbooks in that script right?

Let me ask you for some info about your environment:

- Which OS are you using? (architecture and version)
- How do you implement our playbook in your scripts (obfuscate any data you consider)
- I suppose you use the same architecture as in the previous issue [#214](https://github.com/wazuh/wazuh-ansible/issues/214)

This information will make me able to deeply troubleshoot your problem, thanks in advance.

Thank you for your patience, I'm willing to receive details on it and troubleshoot as soon as possible in order to make it work fine for you.

Best regards

Jose

**Comment by alphaDev23** [comment]
I noticed something in the wazuh-agent playbook that I had previously commented in an attempt to resolve previous issues.  I uncommented and the agents are now installing.  

However, in the case of floating IPs (e.g. Openstack cloud deployment) I notice that the IP reported on the agents in Kibana is the instance IP, e.g. 10.0.0.6 (vs the external floating IP, e.g. 192.168.5.6).  While technically correct from an agent perspective, the public IP is its floating IP.  This may cause issues when machines are on different networks, have different floating IPs, but have the same instance IP.  What are your thoughts on this?

**Comment by jm404** [comment]
Hi @alphaDev23,

This is a known issue we faced previously, I opened the related issue here: https://github.com/wazuh/wazuh/issues/3457 in order to keep track of this.

You can avoid this duplicated IPs by setting `use_source_ip` to `no` in the *ossec.conf* file.

You can find detailed info at https://github.com/wazuh/wazuh/issues/3457#issuecomment-498625783

Also, let me mention our documentation about `auth` parameters:
- https://documentation.wazuh.com/3.9/user-manual/reference/ossec-conf/auth.html


Sorry for the inconveniences, let me know if you need further help

Best regards!

Jose

**Comment by alphaDev23** [comment]
Thank you for your support and opening the related issue.
