### ISSUE TITLE
wazuh-manager.yml not ready for RHEL 8 / CENTOS 8 because of NodeJS repo

### ISSUE THREAD

**Issue by kadafax** [wazuh/wazuh-ansible#274]
Hi there,

Just to say that I'm trying to deploy wazuh manager to a CentOS 8 host and the playbook is failing because of the lack of CentOS/RHEL 8 repo for NodeJS:
https://rpm.nodesource.com/pub_6.x/el/8/x86_64 unsurprisingly throw a 404.

I know it's just a matter of time before resolution, but maybe it should be stated somewhere that currently this way of installing the manager is not working on this version of RHEL/CentOS.

**Comment by xr09** [comment]
Hi @kadafax,

We'll look into this and report back.  This should be realtively simple, I see nodejs is in the new `AppStream` repo.

Thanks for reporting!

**Comment by xr09** [comment]
Hey @kadafax,

Since we're using nodesource's rpm repos we're depending on their releases for this.

I see there's already an [issue](https://github.com/nodesource/distributions/issues/905) for CentOS 8 support, let's wait a bit and see what's their output.

Moreover, an alternative with the AppStream repo could be implemented in the meantime.

Thanks!

**Comment by wverbeek89** [comment]
Hey Guys,

Is there an update on this subject?
I just reïnstalled my server with CentOS 8.0-0.1905 but Node.Js doesn't support it yet :)

Hope that some good brains can fix this, thanks guys!

**Comment by xr09** [comment]
Hi @wverbeek89,

We're making progress on this, right now nodejs is not the issue but some internal changes on the config, working on it.

Remember, starting with version 8 RHEL and CentOS [do not include a default python](https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8/), so in order to execute Ansible successfully you need to install python3 (it's the only one with dnf modules available) and set it as default python with `alternatives --config python`.

You can have a look at this [branch](https://github.com/wazuh/wazuh-ansible/tree/feature-274-centos8-support) with the current changes but I'll keep posting here as I move forward.

Thanks for joining us!

**Comment by kadafax** [comment]
It seems that https://rpm.nodesource.com/pub_6.x/el/8/x86_64/ is getting populated !

**Comment by xr09** [comment]
Updating this issue, the core team is still working on RHEL/CentOS 8 support, it's currently scheduled for `v3.11`. As soon as it gets released we'll get on with it.

**Comment by kadafax** [comment]
Any news ? I am deploying more and more centos8 VMs and it would be great to have wazuh support on it through ansible.

**Comment by xr09** [comment]
Good news @kadafax Wazuh v3.11 with support for CentOS 8 was released just yesterday. Our new Ansible release will be out soon.

**Comment by kadafax** [comment]
Great ! Thank you !

**Comment by xr09** [comment]
Hello @kadafax, quick update. The release is out already but the current tag `3.11.0_7.5.1` has a small bug when installing CentOS 8, please grab the latest version from master which has been fixed already.

Any feedback will be appreciated. Thanks for your patience!

**Comment by xr09** [comment]
This is fixed with latest release https://github.com/wazuh/wazuh-ansible/releases/tag/3.11.1_7.5.1
