### ISSUE TITLE
Adapt molecule tests

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#463]
Hi team,

### Purpose

The main idea is to review, adapt, and migrate each already implemented Molecule scenario to GitHub actions.
- [x] Default: single manager scenario
- [ ] Distributed scenario: clustered manager scenario + connected agents
- [ ] Distributed scenario: Wazuh + ELK
- [ ] Distributed scenario: Wazuh + ELK xpack security
- [ ] Distributed scenario: Wazuh + Open Distro for Elasticsearch
- [ ] Kibana scenario

Regards

**Comment by neonmei** [comment]
Initial implementation is located at branch **feature-adapt-molecule-tests** which features the following scenarios:

- default (wazuh-manager smoke test)
- distributed-wazuh-elk 
- distributed-wazuh-elk-xpack 
- distributed-wazuh-odfe

Kibana scenario is absorbed into the distributed scenarios, which features a working kibana installation (which eventually would be tested with verifier testinfra or ansible). ODFE scenario is not enabled in github actions until another PR improves on security_actions conditionals in opendistro-elasticsearch role. Verifier tests were disabled because they need work alonside roles, this will be addressed on another issue/pr.

As a side note, converge playbooks can be run with `strategy: free` for local testing, but that particular option wasn't included in the branch because it exhausts github runner resources.

For reference, this is a test run for what I recently pushed to the branch: https://github.com/wazuh/wazuh-ansible/runs/1364624802
