### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-ansible#470]
Hi team,

In the Ansible roles for Filebeat, ES and Kibana in both their _ODFE_ and _licensed_ version, there are several unused vars. Hereunder there is a list with these variables. These should be evaluated and used/removed.

#### Elasticsearch/ODFE

- es_version (unused var)
- es_major_version (unused var)
- opendistro_security_password (unused var)
- single_node (unused var in Opendistro role)
- opendistro_cluster_name (unused var in Opendistro role)

#### Filebeat/Filebeat-oss

- filebeat_output_elasticsearch_enabled (unused var in both roles)
- filebeat_create_config (used and declared in Filebeat, declared and unused in Filebeat-oss)
- filebeat_prospectors (unused var)
- filebeat_enable_logging (unused var)
- filebeat_log_level (unused var)
- filebeat_log_dir (unused var)
- filebeat_log_filename (unused var)
- filebeat_ssl_certificate_file (unused var)
- filebeat_ssl_insecure (unused var)
- filebeat_version (used var in filebeat but unused in filebeat oss. Should be applied on fielbeat-oss installations)

#### Kibana/Kibana-oss

- opendistro_security_user (unused)

Greetings,

JP

**Comment by neonmei** [comment]
These cannot be removed, because at the time of this writing they're in use:

* `single_node`: roles/opendistro/opendistro-elasticsearch/templates/elasticsearch.yml.j2
* `opendistro_cluster_name`: roles/opendistro/opendistro-elasticsearch/templates/elasticsearch.yml.j2
* `filebeat_version`: fixed by Zenidd at PR #486
