### ISSUE TITLE
Add new dependency

### ISSUE THREAD

**Issue by darkdecoy** [wazuh/wazuh-ansible#844]
Almalinux 9 requires the dependency chkconfig to sucessfully install a wazuh aio.

#843

**Comment by teddytpc1** [comment]
PR #846 was created. The changes were tested with the `4.3.8` version and are working fine.

**Comment by teddytpc1** [comment]
As `AlmaLinux` is not one of the [recommended](https://documentation.wazuh.com/current/installation-guide/wazuh-server/#requirements) OS versions the PR will not be merged. 
Feel free to use the `844-dependencies` branch anyway.

**Comment by atcommander** [comment]
Almalinux binary compatible rebuild of RHEL so you will have the same issue RHEL 9 as it is built off of the same code base.

**Comment by teddytpc1** [comment]
Hi @atcommander.
I have updated the task to perform the dependency install only in RHEL9. Thanks for making me realize that.

**Comment by atcommander** [comment]
CentOS 7 and 8 are recommended os verisions ([link](https://documentation.wazuh.com/current/quickstart.html)) but Red Hat has decided turn CentOS into [CentOS Stream](https://www.redhat.com/en/topics/linux/what-is-centos-stream) which is one point release ahead of RHEL rather than a binary compatible rebuild that CentOS was.  The community respond with the creation of [Almalinux](https://almalinux.org/) and [Rocky Linux](https://rockylinux.org/about) which are both binary compatible rebuilds of RHEL.  Will CentOS Stream replace CentOS on recommend os versions list or would Almalinux or Rocky Linux be considered in the future as they would be drop in replacements for CentOS?

**Comment by alberpilot** [comment]
Hello @atcommander 

There is a delicate situation. The Wazuh manager has widely tested along too many OS. 
Wazuh indexer and Wazuh dashboard are Opensearch distributions customized by Wazuh. And they have a list of OS, where Rocky and Almalinux (i.e) are not present. 

This doesn't mean that Opensearch, and Wazuh indexer/dashboard don't work on those OS. We know that it does. But, if we include those OS (and others, we have a list) in the recommended list, we want to warranty our users that all the components, with all the plugins, configurations, etc work without problem. The Opensearch CI is not covering this and we are working on it. 

That's why, for now, we are careful granting "official support" to a list of OS where not all the situations were tested in an automated process. We will include it, for sure. CentOS stream, Rocky and Alma.
