### ISSUE TITLE
Improving CI process including staging repositories

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-ansible#849]
The PR pointend to a branch version that has not packages in `pre-release` or `production` repositories are unable to run correctly the GitHub actions because of unavailable packages. We need to include the staging repositories in the CI process. 

The flow should be:
- If the package version exists in production -> use production. 
- If not and if the package version exists in pre-release -> use pre-release.
- If not and if the package version exists in staging -> use staging. 
- If not, show an error explaining that the required version is not built in any repository.

**Comment by teddytpc1** [comment]
I have a few questions about the strategy to implement these changes:
1. What packages should we include in the validation? All the RPM, DEB and Win x86_64/amd64?
2. Should we validate the packages of all the components even if we are going to install, for example, only the manager?
3. I think we should leave a default configuration so the user does not have to execute the package validations and the production repository is selected by default.
4. We should add a new role with the repositories validation tasks and also we should have our own playbooks for CI and internal deployments in order to execute the new role before installing the components.

**Comment by teddytpc1** [comment]
A bash script to validate the packages was developed and pushed to the `849-CI-improvement` branch: [commit](https://github.com/wazuh/wazuh-ansible/pull/858/commits/d326ada41437deae0db420bed7658e7cc319bb0a).

**Comment by teddytpc1** [comment]
The variable `packages_repository` was added in a new file under roles/wazuh/vars/: [repo_vars.yml](https://github.com/wazuh/wazuh-ansible/blob/849-CI-improvement/roles/wazuh/vars/repo_vars.yml).
The `main.yml` of the `wazuh` roles were updated to include the `repo_vars.yml` and modify the `when` condition for the include_vars for each repository (production, pre-release and staging).
The CI tests (default and distributed) were updated to include the new `check-packages` roles. The tests were executed in the PR and are working as expected: [checks](https://github.com/wazuh/wazuh-ansible/pull/858/checks).

**Comment by teddytpc1** [comment]
The [packages_uri.txt](https://github.com/wazuh/wazuh-ansible/blob/d42d9aee04861f003d07104dcc84049e0286e7da/roles/wazuh/check-packages/files/packages_uri.txt) file was updated. The URI of the manager package for DEB was added. The checks succeeded.
Some changes introduced for testing purposes were reverted.

**Comment by teddytpc1** [comment]
Several changes were made to the check packages script in order to make it work with the Windows agent packages stored in the Staging repository. The revision for those packages is not `-1`, so for the Demo deployments the Windows package URI will be added to the `packages_uri.txt` file and the script will look for the last created package for the version we are trying to install in the Staging repository with `aws CLI`.
More detail of the code could be found [here](https://github.com/wazuh/wazuh-ansible/blob/a7c4f3ea7e6b4a1c6f7346458661c2e133284f5c/roles/wazuh/check-packages/scripts/check_packages.sh).

Several tests were made in order to validate the script. It was tested with versions `4.3.9` and `4.4.0` and with and without the Windows package URI in the `packages_uri.txt` file.
