### ISSUE TITLE
Wrong installation directory for Wazuh agent

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#93]
Hi team,

The Ansible playbook for deploying a Wazuh agent is not installing it where the documentation currently [indicates](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html#using-the-gui). According to the official documentation:
```
By default, all agent files will be found in: C:\Program Files(x86)\ossec-agent.
```

Instead, it's being installed in the root `C:/`.

Thanks

**Comment by cadoming** [comment]
Hello, team, 

I have tried to resolve this issue but I have had some problems in the process.

First I did the installation in the path `C:/wazuh-agent` and it works correctly. After this I changed the installation path to `C:/Program Files (x86)/wazuh-agent`, as indicated in the Issue. By doing this the Ansible process is blocked indefinitely in the installation task.

I assumed it was a permission error, so I tried changing the task that downloads the installer to `C:/Program Files (x86)` instead of `C:/`. By doing this I fail to download the installer.

When the installer download task failed I gave all permissions to the administrator and the user(it have admin permissions) for the folder `C:/Program Files (x86)`.  With this I no longer fail the download task of the installer but I still fail the installation task of the agent.

Therefore it is possible that for this reason the default path to install the agent is `C:/wazuh-agent` and not `C:/Program Filex (x86)`.
